services:
  - type: web
    name: portal-academico
    runtime: docker
    repo: https://github.com/TU_USUARIO/portal-academico-gestion-cursos
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: portal-academico-db
          property: connectionString
      - key: Redis__ConnectionString
        sync: false
      - key: Redis__InstanceName
        value: PortalAcademico:
      - key: CacheSettings__CursosCacheDuration
        value: 60

databases:
  - name: portal-academico-db
    databaseName: portalacademico
    user: portalacademico
    plan: free